services:
    db:
        image: postgres:17
        container_name: shared-db
        restart: unless-stopped
        environment:
            POSTGRES_PASSWORD: password
            POSTGRES_DB: db
        volumes:
            - db_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - internal
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres -d db"]
            interval: 5s
            timeout: 5s
            retries: 10

    # specifying the env variables that we need in order to run the container and that other contianer can access kafka broker
    # kafka:
    #     image: apache/kafka:4.3.0
    #     container_name: kafka
    #     environment:
    #         KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
    #         KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
    #         KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafka:9093
    #         KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
    #         KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
    #         KAFKA_CFG_NODE_ID: 0
    #         KAFKA_CFG_PROCESS_ROLES: controller,broker
    kafka:
        image: apache/kafka:4.3.0
        container_name: kafka
        environment:
            KAFKA_LOG4J_ROOT_LOGLEVEL: WARN
            KAFKA_NODE_ID: 0
            KAFKA_PROCESS_ROLES: broker,controller

            KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094

            KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
            KAFKA_CONTROLLER_QUORUM_VOTERS: 0@kafka:9093
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT

            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
            KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
            KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
        ports:
            - "9092:9092"
            - "9094:9094"
        networks:
            - internal

    patient-service:
        build:
            context: ./patient-service
            dockerfile: dockerfile
        container_name: patient-service
        restart: "no"
        depends_on:
            db:
                condition: service_healthy
            billing-service:
                condition: service_started
        environment:
            DB_HOST: shared-db
            DB_PORT: 5432
            DB_NAME: db
            DB_PASSWORD: password
            BILLING_SERVICE_ADDRESS: billing-service
            BILLING_SERVICE_GRPC_PORT: 9001
        ports:
            - "4000:4000"
        networks:
            - internal

    billing-service:
        build:
            context: ./billing-service
            dockerfile: dockerfile
        container_name: billing-service
        restart: "no"
        # depends_on:
        #     - db
        # environment:
        #     DB_HOST: shared-db
        #     DB_PORT: 5432
        #     DB_NAME: db
        #     DB_PASSWORD: password
        ports:
            - "4001:4001"
            - "9001:9001"
        networks:
            - internal

networks:
    internal:
        driver: bridge

volumes:
    db_data: