server:
  port: 4004

logging:
  level:
    root: WARN
    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: DEBUG
    # root: INFO
    # org.springframework.cloud.gateway: DEBUG

auth:
  service:
    url: http://auth-service:4005/auth

spring:
  output:
    ansi:
      enabled: ALWAYS

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: patient-service-route
              uri: http://host.docker.internal:4000
              predicates:
                - Path=/api/patients,/api/patients/**
              filters:
                - StripPrefix=1
                - JwtValidation

            - id: api-docs-patient-route
              uri: http://host.docker.internal:4000
              predicates: 
                - Path=/api-docs/patients
              filters:
                - RewritePath=/api-docs/patients,/v3/api-docs

            - id: auth-service-route
              uri: http://host.docker.internal:4005
              predicates:
                - Path=/api/auth/**
              filters:
                - StripPrefix=1
